GET http://localhost:3001/products


### create a product
POST http://localhost:3001/products

###
GET http://localhost:3001/products/id

###

PATCH  http://localhost:3001/products/id

###
DELETE  http://localhost:3001/products/id

###
GET http://localhost:3001/